#!/bin/bash

echo ''
echo '########################################################################' 
echo '###                                                                  ###' 
echo '###                 Welcome to the nubis-proxy project               ###' 
echo '###  Find us on GitHub https://github.com/nubisproject/nubis-proxy   ###' 
echo '###           Reach out on irc.mozilla.org in #nubis-users           ###' 
echo '###       Shoot us a message nubis-users[at]googlegroups.com         ###' 
echo '###                                                                  ###' 
echo '########################################################################' 
